#!/bin/bash

## Open folders in nautilus

close_dash() {
    $HOME/.config/eww/./toggle_dashboard.sh 
}

if [[ "$1" == "--dl" ]]; then
	close_dash && nautilus ~/Downloads &

elif [[ "$1" == "--docs" ]]; then
	close_dash && nautilus ~/Documents &

elif [[ "$1" == "--music" ]]; then
	close_dash && nautilus ~/Music &

elif [[ "$1" == "--pics" ]]; then
	close_dash && nautilus ~/Pictures &

elif [[ "$1" == "--cfg" ]]; then
	close_dash && nautilus ~/.config &

elif [[ "$1" == "--local" ]]; then
	close_dash && nautilus ~/.local/share &

fi
