from pathlib import Path

WIDGET_FILE = "../widgets/generated-todo.yuck"

def parse_unchecked_items(md_file):
    unchecked = []
    with open(md_file, "r", encoding="utf-8") as f:
        for line in f:
            stripped = line.strip()
            if stripped.startswith("- [ ]"):
                content = stripped[5:].strip()
                unchecked.append(content)
    return unchecked

def escape_yuck_text(text):
    return text.replace("\\", "\\\\").replace("\"", "\\\"")

def format_combined_labels(section_title, items):
    lines = [f'            (label :text "{escape_yuck_text(section_title)}:" :class "todo-section" :halign "start" )']
    for item in items:
        lines.append(f'            (label :text " {escape_yuck_text(item)}" :class "todo-item" :halign "start" )')
    return lines

def main():
    files = {
        "Personal": "~/Notes-Obsidian/Obsidian_Vaults/Personal/Notes/TODO-Personal.md",
        "Uni": "~/Notes-Obsidian/Obsidian_Vaults/Uni/Notes/Uni-TODO.md"
    }

    all_labels = []
    total_tasks = 0

    for section, filepath in files.items():
        path = Path(filepath).expanduser()
        if path.exists():
            items = parse_unchecked_items(path)
            total_tasks += len(items)
            if items:
                all_labels += format_combined_labels(section, items)
            else:
                all_labels += format_combined_labels(section, [f"No tasks 🎉"])
        else:
            all_labels += format_combined_labels(section, [f"File Not Found!"])

    widget_lines = [
        ";; THIS FILE IS AUTO-GENERATED BY todo.py. DO NOT EDIT MANUALLY.",
        "(defwidget todo-list []",
        "  (box :class \"genwin\"",
        "    (box :orientation \"v\" :spacing 10 :space-evenly \"false\" :vexpand \"false\" :hexpand \"false\"",
        "      ;; Header section with item count",
        "      (box :orientation \"h\" :space-evenly \"false\"",
        "        (label :text \"\" :class \"icontodo\":halign \"end\" )",
        f"        (label :text \"{total_tasks} items\" :class \"label-todo\" )",
        "        (box :orientation \"v\" :class \"list-style\""
    ]

    widget_lines += all_labels

    widget_lines += [
        "        )",  # close list-style box
        "      )",    # close header/content row
        "    )",      # close outer vertical box
        "  )",        # close genwin
        ")"          # end defwidget
    ]

    with open(WIDGET_FILE, "w", encoding="utf-8") as f:
        f.write("\n".join(widget_lines))

if __name__ == "__main__":
    main()
